import test from 'node:test';
import assert from 'node:assert/strict';
import { bootstrap } from '../src/core/bootstrap.js';
import { routeQuestion } from '../src/core/router.js';
import { retrieve } from '../src/core/retrieval.js';
import { generateSellerAnswer } from '../src/core/generator.js';
import { evaluateAnswer } from '../src/core/evaluator.js';
import { runEvaluation } from '../src/core/evaluation-runner.js';
import { generateContent } from '../src/core/content.js';
import { createEmbedding, generateStructuredSellerAnswer } from '../src/providers/openai.js';
import { getSeller } from '../src/data/sellers.js';
import { stages } from '../src/data/stages.js';
import { getSkill } from '../src/core/skills.js';
import type { SellerAnswer } from '../src/types/index.js';

test('bootstrap exposes five journey stages', async()=>assert.equal((await bootstrap()).stages.length,5));
test('bootstrap exposes four sellers', async()=>assert.equal((await bootstrap()).sellers.length,4));
test('bootstrap loads six agent skills', async()=>assert.ok((await bootstrap()).agents.length>=6));
test('routes opportunity questions', async()=>assert.equal((await routeQuestion('Why should I expand beyond the US?')).agentId,'global-opportunity'));
test('routes compliance questions', async()=>assert.equal((await routeQuestion('进入德国需要哪些认证？')).agentId,'compliance-education'));
test('routes launch questions', async()=>assert.equal((await routeQuestion('What blocker should we close before launch?')).agentId,'launch-coach'));
test('retrieval returns ranked lexical evidence', async()=>{const r=await retrieve('inventory inbound replenishment',2);assert.equal(r.length,2);assert.equal(r[0]?.retrievalMode,'lexical');});
test('retrieval exposes source metadata', async()=>{const [r]=await retrieve('compliance market requirements',1);assert.ok(r?.file.endsWith('.md'));});
test('generator returns seller context and evidence', async()=>{const q='How should we plan inbound inventory?';const route=await routeQuestion(q);const a=await generateSellerAnswer({question:q,sellerId:'gz-home',route});assert.ok(a.sellerContext);assert.ok(a.evidence.length>0);});
test('generator supports Mandarin', async()=>{const q='进入德国需要哪些认证？';const route=await routeQuestion(q);const a=await generateSellerAnswer({question:q,sellerId:'sz-electronics',route});assert.ok(a.cta.length>0);});
test('evaluator rewards complete answers', ()=>{const a:SellerAnswer={headline:'H',summary:'S',actions:[{text:'A',status:'recommended'}],guardrail:'G',cta:'C',provider:'deterministic',sellerContext:'Seller',evidence:[{source:'x.md',excerpt:'E',score:1,retrievalMode:'lexical'}]};assert.equal(evaluateAnswer(a).score,100);});
test('evaluator detects prohibited claims', ()=>{const a:SellerAnswer={headline:'H',summary:'guaranteed revenue growth',actions:[{text:'A',status:'recommended'}],guardrail:'G',cta:'C',provider:'deterministic',sellerContext:'Seller',evidence:[{source:'x.md',excerpt:'E',score:1,retrievalMode:'lexical'}]};assert.equal(evaluateAnswer(a).checks.noProhibitedClaims,false);});
test('evaluation covers 24 labeled cases', async()=>assert.equal((await runEvaluation()).summary.cases,24));
test('evaluation routes all included cases', async()=>assert.equal((await runEvaluation()).summary.routingAccuracy,100));
test('content generator returns typed content', ()=>{const c=generateContent({sellerId:'sz-electronics',format:'checklist',language:'zh'});assert.equal(c.format,'checklist');assert.ok(c.body.length>0);});
test('OpenAI adapters parse mocked responses', async()=>{const oldFetch=globalThis.fetch;const oldKey=process.env.OPENAI_API_KEY;process.env.OPENAI_API_KEY='test-key';let n=0;globalThis.fetch=async()=>{n++;return n===1?new Response(JSON.stringify({data:[{embedding:[0.1,0.2]}]}),{status:200,headers:{'Content-Type':'application/json'}}):new Response(JSON.stringify({output_text:JSON.stringify({headline:'H',summary:'S',actions:[{text:'A',status:'recommended'}],guardrail:'G',cta:'C'})}),{status:200,headers:{'Content-Type':'application/json'}})};try{assert.deepEqual(await createEmbedding('x'),[0.1,0.2]);const r=await generateStructuredSellerAnswer({question:'Why expand?',seller:getSeller('sz-electronics'),skill:await getSkill('global-opportunity'),stage:stages[0]!,evidence:[],readiness:{band:'medium',score:74,strengths:[],gaps:[],disclaimer:'test'},language:'en'});assert.equal(r.provider,'openai');}finally{globalThis.fetch=oldFetch;if(oldKey===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=oldKey;}});
